# yaml(*.yml)
#     yet another markup language
#     가벼운 마크업 언어로 사용
#
# 기본 문법
#   # 는 주석
#   기본표현
#      key: value     <- : 다음에는 반드시 공백문자가 와야 함
#
#   key:
#       key_1:
#           key_2:
#               key_3:
#                   ..


# 서버 포트 번호
server:
  port: 8080

spring:
  #콘솔 ANSI 색상
  output:
    ansi:
      enabled: always

  # Thymeleaf 설정
  thymeleaf:
    cache: false
    prefix: classpath:templates/views/

  # datasource 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb2309?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: myuser2309
    password: 1234

# security 설정
  security:
    user:
      name: user
      password: 1111

# MyBatis 매퍼(mapper) 파일 위치 설정
# src/main/resources 이하의 경로 지정
mybatis:
  mapper-locations: classpath:mapper/**/*.xml











